\context ChordNames
	\chords {
		\set chordChanges = ##t

		% intro
		r1
		c1 bes1 f1 c1
		c1 bes1 f1 g1

		% estrofa 1
		c1 bes1 f1 c1
		c1 bes1 f1 c1 d1:m
		f1 g1 c1 g1

		% estrofa 2
		c1 bes1 f1 c1
		c1 bes1 f1 c1 d1:m
		f1 g1 c1 g1

		% estribillo
		d1:m g1 e1:7 a1:m
		d1:/fis f1 d1:m g1
		d1:m g1 e1:7 a1:m
		d1:/fis f1 d1:m g1

		% enlace
		c1 bes1 f1 g1

		% estrofa 3
		c1 bes1 f1 c1
		c1 bes1 f1 c1 d1:m
		f1 g1 c1 g1

		% estribillo
		d1:m g1 e1:7 a1:m
		d1:/fis f1 d1:m g1
		d1:m g1 e1:7 a1:m
		d1:/fis f1 d1:m g1

		% enlace
		c1 bes1 f1 g1

		% coda
		aes1 ees1 des1 aes1
		f1 bes1:m d1:7 g1

		% estribillo
		d1:m g1 e1:7 a1:m
		d1:/fis f1 d1:m g1
		d1:m g1 e1:7 a1:m
		d1:/fis f1 d1:m g1

		% enlace
		e1 a1:7

		% estribillo en d
		e1:m a1 fis1:7 b1:m
		e1:/gis g1 e1:m a1
		e1:m a1 fis1:7 b1:m
		e1:/gis g1 e1:m a1

		% outro
		e1:m a1
		d1
	}
